config = dict(
    project_root='/Users/benj/Documents/Research/Projects/disease-time-series/',
    representation='pca',
    pca_components=3,
    cca_components=3,
    kmeans_clusters=115,
    time_transform=False,
    gp_type='rbf',
    gp_lengthscale=5,
    gp_variance=4,
    clean_components=3,
    clean_data=True,
    cca_reg=0.0001,
    view_pca_plots=False,
    transpose_data=False,
    filter_include_nan=True,
)
